name: in_pack
description: project for social smokers.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"


dependencies:
  # Base
  cupertino_icons: ^1.0.2
  cloud_firestore:
  firebase_core:
  firebase_auth: ^3.4.1
  firebase_storage:
  flutter_bloc: ^8.0.0
  json_annotation: ^4.6.0
  bloc:
  meta:
  flutter:
    sdk: flutter
  file_picker:
  image_picker:
  path_provider:
  faker:
  mime:
  http:
  equatable:
  cached_network_image: ^3.2.1
  flutter_map:
  flutter_map_marker_cluster: ^0.5.0
  geolocator: ^9.0.1
  permission_handler:
  latlong2:

dev_dependencies:
  flutter_lints: ^2.0.0
  json_serializable: ^6.3.1
  build_runner: 
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
     - assets/images/

  fonts:
     - family: Roboto
       fonts:
         - asset: fonts/Roboto-Regular.ttf
     - family: Gantari
       fonts:
         - asset: fonts/Gantari-VariableFont_wght.ttf
     - family: SF
       fonts:
         - asset: fonts/SF-Pro.ttf