name: in_pack
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"


dependencies:
  cloud_firestore:
  firebase_core:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_chat_ui: ^1.6.3
  flutter_chat_types: ^3.4.3
  firebase_auth: ^3.4.1
  flutter_firebase_chat_core: ^1.6.2
  file_picker:
  image_picker:
  path_provider:
  open_file:
  firebase_storage:
  faker:
  mime:
  http:
  flutter_map_marker_cluster: ^0.5.0
  flutter_map:
  latlong2:
  permission_handler:
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
     - assets/Pavel.jpg

  fonts:
     - family: Gantari
       fonts:
         - asset: fonts/Gantari-VariableFont_wght.ttf
     - family: SF
       fonts:
         - asset: fonts/SF-Pro.ttf